// +build !ignore_autogenerated

/*
Copyright 2021 AstroKube.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSElasticContainerRegistry) DeepCopyInto(out *AWSElasticContainerRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSElasticContainerRegistry.
func (in *AWSElasticContainerRegistry) DeepCopy() *AWSElasticContainerRegistry {
	if in == nil {
		return nil
	}
	out := new(AWSElasticContainerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSelector) DeepCopyInto(out *ImageSelector) {
	*out = *in
	if in.MatchRegexp != nil {
		in, out := &in.MatchRegexp, &out.MatchRegexp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchExact != nil {
		in, out := &in.MatchExact, &out.MatchExact
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchHostRegexp != nil {
		in, out := &in.MatchHostRegexp, &out.MatchHostRegexp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchHostExact != nil {
		in, out := &in.MatchHostExact, &out.MatchHostExact
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSelector.
func (in *ImageSelector) DeepCopy() *ImageSelector {
	if in == nil {
		return nil
	}
	out := new(ImageSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCredentials) DeepCopyInto(out *RegistryCredentials) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCredentials.
func (in *RegistryCredentials) DeepCopy() *RegistryCredentials {
	if in == nil {
		return nil
	}
	out := new(RegistryCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryCredentials) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCredentialsList) DeepCopyInto(out *RegistryCredentialsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegistryCredentials, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCredentialsList.
func (in *RegistryCredentialsList) DeepCopy() *RegistryCredentialsList {
	if in == nil {
		return nil
	}
	out := new(RegistryCredentialsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryCredentialsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCredentialsSpec) DeepCopyInto(out *RegistryCredentialsSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	in.ImageSelector.DeepCopyInto(&out.ImageSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCredentialsSpec.
func (in *RegistryCredentialsSpec) DeepCopy() *RegistryCredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryCredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCredentialsStatus) DeepCopyInto(out *RegistryCredentialsStatus) {
	*out = *in
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
	if in.AuthenticatedTime != nil {
		in, out := &in.AuthenticatedTime, &out.AuthenticatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCredentialsStatus.
func (in *RegistryCredentialsStatus) DeepCopy() *RegistryCredentialsStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryCredentialsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryProvider) DeepCopyInto(out *RegistryProvider) {
	*out = *in
	if in.AWSElasticContainerRegistry != nil {
		in, out := &in.AWSElasticContainerRegistry, &out.AWSElasticContainerRegistry
		*out = new(AWSElasticContainerRegistry)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryProvider.
func (in *RegistryProvider) DeepCopy() *RegistryProvider {
	if in == nil {
		return nil
	}
	out := new(RegistryProvider)
	in.DeepCopyInto(out)
	return out
}
